repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        files: \.(md|yml|yaml|sql)$
      - id: end-of-file-fixer
        files: \.(md|yml|yaml|sql)$
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.0.0
    hooks:
      - id: sqlfluff-lint
        args: [--dialect, snowflake, --templater, jinja]
        additional_dependencies: ['dbt-snowflake>=1.0.0']
      - id: sqlfluff-fix
        args: [--dialect, snowflake, --templater, jinja, --force]
        additional_dependencies: ['dbt-snowflake>=1.0.0']

  - repo: local
    hooks:
      - id: check-release-version
        name: Check Release Version
        entry: ./scripts/check-version.sh
        language: script
        files: ^(dbt_project\.yml|CHANGELOG\.md|README\.md)$
        pass_filenames: false
        description: Validates version consistency and changelog entries for releases
