---
extends: default

ignore: |
  target/
  dbt_packages/
  logs/
  .history/
  **/package-lock.yml

rules:
  line-length:
    max: 120
  indentation:
    spaces: 2
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: false
  document-start:
    present: true
