---
name: 'yuki_snowflake_dbt_tags'
version: '0.2.4'
config-version: 2

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Specify dbt's version requirement
require-dbt-version: [">=1.0.0"]

# Configure package-specific settings
dispatch:
  - macro_namespace: dbt
    search_order:
      - yuki_snowflake_dbt_tags
      - dbt
