name: 'yuki_snowflake_dbt_tags'
version: '0.1.0'
config-version: 2

# (Optional) Specify dbt's version requirement if needed
require-dbt-version: [">=0.18.0"]

# Dependencies (if you have any, like other packages)
dependencies: []