name: Test Package

on:
  push:
    branches: [main, develop, prepare_for_publication]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

jobs:
  test-integration:
    runs-on: ubuntu-latest
    name: Test Integration Tests

    env:
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      DBT_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      DBT_SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      DBT_SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      DBT_SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      DBT_SNOWFLAKE_SCHEMA: dbt_integration_tests_ci

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core>=1.0.0 dbt-snowflake>=1.0.0

      - name: Create test profiles.yml
        run: |
          mkdir -p ./ci/profiles
          cat > ./ci/profiles/profiles.yml << EOF
          config:
            send_anonymous_usage_stats: false

          yuki_snowflake_dbt_tags_integration_tests:
            target: test
            outputs:
              test:
                type: snowflake
                account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
                user: "{{ env_var('DBT_SNOWFLAKE_USER') }}"
                password: "{{ env_var('DBT_SNOWFLAKE_PASSWORD') }}"
                role: "{{ env_var('DBT_SNOWFLAKE_ROLE') }}"
                database: "{{ env_var('DBT_SNOWFLAKE_DATABASE') }}"
                warehouse: "{{ env_var('DBT_SNOWFLAKE_WAREHOUSE') }}"
                schema: "{{ env_var('DBT_SNOWFLAKE_SCHEMA') }}"
                threads: 1
          EOF

          # Set DBT_JOB_NAME environment variable for query tagging
          echo "DBT_JOB_NAME=ci-test-$(date +%Y%m%d-%H%M%S)" >> $GITHUB_ENV

      - name: Install package dependencies
        run: |
          cd integration_tests
          dbt deps --profiles-dir ../ci/profiles

      - name: Run integration tests
        run: |
          cd integration_tests
          echo "Running integration tests with dbt build..."
          dbt build --profiles-dir ../ci/profiles
