name: Test Package

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch: {}

env:
  DBT_JOB_NAME: ci-integration-test
  CI_RUNNER_TAGS: ubuntu-latest

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
      DBT_SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
      DBT_SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
      DBT_SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
      DBT_SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
      DBT_SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
      DBT_SNOWFLAKE_SCHEMA: dbt_integration_tests_ci

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          pip install dbt-core>=1.0.0 dbt-snowflake>=1.0.0

      - name: Install dependencies
        run: |
          cd integration_tests
          dbt deps

      - name: Run tests
        run: |
          cd integration_tests
          dbt build
